name: 'wait-argocd'
description: 'Sanitize a string for kubernetes names'
inputs:
  argo_endpoint:
    description: 'Argocd endpoint'
    required: true
    default: ''
  argo_user:
    description: 'Argocd user'
    required: true
    default: ''
  argo_password:
    description: 'Argocd password'
    required: true
    default: ''
  application_name:
    description: 'Application name to wait for'
    required: true
    default: ''
  max_retries:
    description: 'Max retries'
    required: true
    default: '10'
  wait_ms:
    description: 'Max retries'
    required: true
    default: '5000'
    
runs:
  using: 'node20'
  main: 'dist/index.js'